### PR TITLE
Action: Learn Bystander Intervention

### PR DESCRIPTION
**Pull request by elizabethyalkut**
I don't love the image I grabbed, so feel free to change that. It's *hard* to visualize bystander intervention!

### CODE REVIEW

**Comment by shoshi** [comment]
I love this idea! Do they offer any resources for free? I'm wary of promoting something that charges for this sort of thing. I understand everybody has to make a living, even when you're doing good things. It feels a little exclusionary for putting on this site though.

**Comment by elizabethyalkut** [comment]
Not that I'm aware of; this is sliding scale, though, as low as $5, and we're already posting donation opportunities.

**Comment by shoshi** [comment]
The sliding scale is definitely helpful. It is true that we have donation actions. I think for donations, people in need can also benefit from those organization's free services if they're on the other side of the interaction. Paid events seem a little bit different to me, though the difference is hard to quantify exactly. I guess if you need support it should be free, and if you want to help those who need support you can offer your money? I realize the middle is quite grey.

They do have a free app, maybe we could publish that? https://www.ihollaback.org/get-app/

**Comment by shoshi** [comment]
I think I've found a middle ground! They have a free guide: https://www.ihollaback.org/resources/bystander-resources/ yay! We could make that the main action, and link to the webinars in the text if people want to learn even more. That way the main action is free, and sliding-scale paid events are a bonus. I'm happy to merge it and make the changes if this sounds good to you?

**Comment by elizabethyalkut** [comment]
+1

**Pull request merged**
